name: Close Pull Requests

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Close stale pull requests
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639
        with:
          days-before-issue-stale: -1  # Don't auto-close issues
          days-before-stale: 1
          days-before-close: 0
          stale-pr-message: 'This pull request has been automatically closed.'
          stale-pr-label: stale

